name: Run API Tests with Newman

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Newman
      run: npm install -g newman

    - name: Run Newman tests
      run: |
        newman run login-tests.postman_collection.json --reporters cli,junit --reporter-junit-export results.xml
